language: cpp

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libfftw3-dev
      - libgsl-dev
      - libncurses-dev

matrix:
  include:
  - os: linux
    addons:
      apt:
        packages:
        - g++-7
    env: COMPILER=gcc GCC=7
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
    env: COMPILER=clang CLANG=5
  - os: osx
    osx_image: xcode9.1
    compiler: clang

before_install:
- |
  # Configure build variables
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    if [[ "$COMPILER" == "gcc" ]]; then
      export CXX=g++-$GCC CC=gcc-$GCC;
    fi
    if [[ "$COMPILER" == "clang" ]]; then
      export CXX=clang++-$CLANG CC=clang-$CLANG;
    fi
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export CXX=clang++ CC=clang;
  fi
install:
# Testing
- mkdir $TRAVIS_BUILD_DIR/build
- cd $TRAVIS_BUILD_DIR/build
- cmake ..
- make -j2
#script:
#- run_test
