language: cpp

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: "o/46Dvf4DzhOqWhsHEQ+uwgd2bo3sGKHbiWyn9PfqDktf1FiBS9DpKdHUAEpAAdMmQKnzYYUqHqCJzcXtdntgas1vZOFigO/TkocyRQ9IJXFJV4JC8qRJrnYAaQYJ0PcxftHbHSLtmKEPYqZhAyPb220HkRVsuSFyL8PG9Zxk+Ub0pfBECx/ueeg8jCXtqrbgQitaSwVj7lLVi4xv2lwSeKF8vabPTv+ZBGPdDHzeq2sJvuxqoKgyHWslTq3hiFCdwoEOn6oL3S5OFVXyBSKb4aZv5LUwxWo57TqFm01W42o1J1sz9vfjtsl4mDTkGkQs1BfSichL+KR4OxiFvBi4a7sjl1naYhYqyC1F0VvKLMHOTT8nx8HDA03HqALnxwHkEfy4GGveSwVBxFtvfTvipspNDSBU4muS8i22v5HfMv48cgkFIlJGJOOzWnK9mvVD6taET1RHBKUPKWfHukVf6dG1q/o/NqoFB2sn3eQuRUFpR+i9ulEkVpVmty4g95/IhNQiXf/iVhez+eaBEWAdSQMnvifTmA1e04kYpfcXM7nGb9CB1aESBnByxlLT/8extpX+PQaXurxGhpuKZaasRpdDLtd2Nrg6UYxBggxPinzxZ+hHD7KRF1efu2IgToqufFi+Bim5tkqJ3Di2LUvOkY+w0cojPPHLLujE2xQ+Kc="

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libfftw3-dev
        - libgsl0-dev
        - libncurses-dev
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
        - libfftw3-dev
        - libgsl0-dev
        - libncurses-dev
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
  - os: osx
    osx_image: xcode10
    compiler: clang

before_install:
- eval "${MATRIX_EVAL}"
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget "http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda update -yq conda
    conda install -y cmake gsl fftw -c conda-forge
  fi

addons:
  coverity_scan:
    project:
      name: "egpbos/barcode"
      description: "Bayesian reconstruction of cosmic density fields"
    notification_email: egpbos@gmail.com
    build_command_prepend: "mkdir $TRAVIS_BUILD_DIR/build; cd $TRAVIS_BUILD_DIR/build; cmake .."
    build_command: "make"
    branch_pattern: coverity_scan

script:
# Build
- mkdir $TRAVIS_BUILD_DIR/build
- cd $TRAVIS_BUILD_DIR/build
- cmake ..
- make -j2
# Testing
- |
  cd $TRAVIS_BUILD_DIR/test
  $TRAVIS_BUILD_DIR/build/test/io_array
  $TRAVIS_BUILD_DIR/build/test/parameter_input_file
  cd -
